apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "httpd.fullname" . }}
  labels:
    {{- include "httpd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "httpd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "httpd.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "httpd.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
